package mainpanel;

public enum JarEditButtons {
    ADD_PACKAGE,
    DELETE_PACKAGE,
    ADD_CLASS,
    DELETE_CLASS,
    ADD_INTERFACE,
    ADD_METHOD,
    DELETE_METHOD,
    EDIT_METHOD,
    ADD_FIELD,
    DELETE_FIELD,
    SET_FIELD_PUBLIC,
    SET_FIELD_PROTECTED,
    SET_FIELD_PRIVATE,
    SET_FIELD_STATIC,
    SET_METHOD_PUBLIC,
    SET_METHOD_PROTECTED,
    SET_METHOD_PRIVATE,
    SET_METHOD_STATIC
}
